server:
  maxplayers: 16
  tickrate: 20
  map: "gm_flatgrass"
  ip: "0.0.0.0"
  port: 0
  workshop_clients: "177294269"
  workshop_server: "2371557248"
  gamemode: "spaceage"
  restart_every: "24h"
addons:
- name: SpaceAge
  private: yes
  trusted: yes
  gamemodes:
    - spaceage
- name: sbep
- name: spacebuild
  gamemodes:
    - spacebuild
- name: multi-parent
- name: physgun-build-mode
- name: Falcos-Prop-protection
- name: Joystick
- name: smartsnap
- name: wire-extras
  repo: https://github.com/wiremod/wire-extras
  branch: master
- name: lua_reloadent
  repo: https://github.com/TomyLobo/lua_reloadent
  branch: master
- name: sentry
  repo: https://github.com/Lexicality/gmod-sentry
  branch: master
luabins:
- name: luaerror
  type: github_release
  config:
    org: SpaceAgeMP
    name: gm_luaerror
- name: random
  type: github_release
  config:
    org: SpaceAgeMP
    name: gmsv_random
- name: gwsockets
  type: github_release
  config:
    org: SpaceAgeMP
    name: GWSockets
